language: php
php:
  - 5.6
  - 7.0
  - hhvm
sudo: false
cache:
  directories:
    - $HOME/.composer/cache
before_script:
  - composer self-update
  - composer install
script:
  - phpunit
after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi
